name: Update code on server
on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: anacreon
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy to home
        run: |
          echo "Copying code to home directory..."
          rsync -a --delete --exclude='.git' ./ /var/www/snc2024/
          echo "Code copied successfully."
testetest

